import {StyleSheet, Dimensions} from 'react-native';
const {width, height} = Dimensions.get('screen');
const styles = StyleSheet.create({
  Allphoto: {
    justifyContent: 'center',
    alignItems: 'center',
    height: 100,
    width: (width - 10) / 3,
    margin: 0,
    padding: 0,
  },
  MainContainer: {
    width: width,
    height: height * 0.72,
    backgroundColor: '#123',
    // backgroundColor: '#F9F68F',
    // paddingTop: 0,
    // margin: 0,
    // flex : 1
  },
  MainContainerSearch: {
    width: width,
    height: height * 0.76,
    backgroundColor: '#123',
    // backgroundColor: '#F9F68F',
    // paddingTop: 0,
    // margin: 0,
    // flex : 1
  },
  MainView: {
    backgroundColor: '#F9F68F',
    flex: 1,
    padding: 0,
    margin: 0,
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  titleNote: {
    fontWeight: '600',
  },
  textNote: {
    fontSize: 10,
  },
  RecipeImage: {
    justifyContent: 'center',
    alignItems: 'center',
    height: width / 4 - 40,
    width: width / 4 - 40,
    //marginBottom:10,
    marginTop: 10,
    marginLeft: 20,
    marginRight: 20,
    resizeMode: 'cover',
    borderWidth: 1,
    borderColor: '#000',
    borderRadius: 150,
    padding: 0,
  },
  UserImage: {
    justifyContent: 'center',
    alignItems: 'center',
    height: width / 2 - 40,
    width: width / 2 - 40,
    //marginBottom:10,
    marginTop: 10,
    marginLeft: 20,
    marginRight: 20,
    resizeMode: 'cover',
    borderWidth: 1,
    borderColor: '#000',
    borderRadius: 150,
    padding: 0,
  },
  buttonSearch: {
    height: height * 0.06,
    backgroundColor: '#484c7f',
  },
  TitleScreen:{color:'#fff',marginBottom:20,fontSize:20,textAlign:'right'},
  RecipeTitle: {
    //  '#07E97899'
    // 5eFF1999
    flex: 1,
    flexDirection: 'column',
    // padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    width: width,
    height: '100%',
    borderRadius: 15,

    // borderBottomRightRadius: 15,
    // borderBottomLeftRadius: 15,
  },
  HCCTitle: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-end',
    width: width,
    height: '100%',
    borderRadius: 15,
  },
  AppBooking: {
    flexDirection: 'column',
    margin: 3,
    backgroundColor: '#8977F1',
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    height:height * 0.14
  },
  Note: {
    flexDirection: 'column',
    // justifyContent: 'space-between',
    // alignItems: 'center',
    height: width / 2 - 30,
    width: width / 2 - 30,
    margin: 15,
    // padding: 10,
  },
  buttonFooter: {
    height: 45,
    backgroundColor: '#67FA19',
    marginTop: 5,
    marginLeft: 0,
    marginRight: 0,
    width: 80,
    justifyContent: 'center',
    alignItems: 'center',
    fontWeight: 'bold',
  },
  buttonEdit: {
    height: height * 0.1,
    marginTop: 5,
    marginLeft: 0,
    marginRight: 0,
    width: 80,
    justifyContent: 'center',
    alignItems: 'center',
    fontWeight: 'bold',
  },
  iconFooter: {},
  headerBodyP: {
    // flexDirection: 'row-reverse',
    width: width * 0.7,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 8,
    // margin:8
  },
  headerLeftP: {
    flexDirection: 'row',
    width: width * 0.2,
    justifyContent: 'flex-start',
    alignItems: 'center',
    padding: 8,
  },
  headerRightP: {
    width: width * 0.1,
    justifyContent: 'center',
    alignItems: 'flex-end',
    padding: 8,
  },
  title: {
    fontSize: 30,
    fontFamily: 'Quick Kiss Personal Use',
    color: '#f1d4d4',
    fontWeight: '900',
    fontStyle: 'normal',
    marginBottom: 8,
    // marginTop:8,
    paddingBottom: 8,
    textAlign: 'center',
    // paddingTop:8
    // paddingVertical:8,
    // marginVertical: 10,
  },
  selectFont: {borderWidth: 2, borderColor: '#fff', margin: 10},
});
export default styles;
